project:
  type: book
  resources:
    - CNAME
    - slides/

book:
  title: "Python for Clinical Study Reports and Submission"
  author:
    - Yilong Zhang
    - Nan Xiao
  description: |
    Learn how to prepare tables, listings, and figures for
    clinical study report and submit to regulatory agencies,
    the essential part of clinical trial development.

  output-file: "pycsr"

  cover-image: "assets/cover.jpg"
  image: "assets/preview.png"
  favicon: "assets/favicon.png"

  site-url: https://pycsr.org/
  repo-url: https://github.com/nanxstats/pycsr
  repo-actions: [edit, issue, source]
  sharing: [twitter, linkedin]
  reader-mode: true

  open-graph:
    image: assets/preview.png
    description: |
      Learn how to prepare tables, listings, and figures for
      clinical study report and submit to regulatory agencies,
      the essential part of clinical trial development.
  twitter-card:
    image: assets/preview.png
    description: |
      Learn how to prepare tables, listings, and figures for
      clinical study report and submit to regulatory agencies,
      the essential part of clinical trial development.
    card-style: summary_large_image

  chapters:
    - index.qmd
    - preface.qmd
    - part: "Environment and toolchain"
      chapters:
        - env-dev.qmd
        - env-uv.qmd
        - env-pkg.qmd
    - part: "Clinical trial project"
      chapters:
        - tlf-overview.qmd
        - tlf-disposition.qmd
        - tlf-population.qmd
        - tlf-baseline.qmd
        - tlf-ae-summary.qmd
        - tlf-ae-specific.qmd
        - tlf-efficacy-ancova.qmd
    - part: "Analysis package"
      chapters:
        - pkg-overview.qmd
        - pkg-structure.qmd
        - pkg-management.qmd
    - part: "eCTD submission"
      chapters: 
        - submission-overview.qmd
        - submission-package.qmd
        - submission-dryrun.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: [cosmo, custom.scss]
    mainfont: "Lato, system-ui, -apple-system, Segoe UI, Roboto, Helvetica Neue, Noto Sans, Liberation Sans, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol, Noto Color Emoji"
  pdf:
    documentclass: scrreprt
